<h2>Agregar Cuenta</h2>

<div class="container">
	<div class="col-sm-6 col-md-8 mx-auto">
<form action="<?php
/**
 * add.php
 *
 * @author Arturo Adonay Rayas Vergara <arturorayas60@gmail.com>
 */
 echo APP_URL.'accounts/add'; ?>" method="POST">
	<div class="form-group">
		<label for="name">Nombre</label>
		<input type="text" class="form-control" name="name">
	</div>
		<button class="btn btn-sm btn-success pull-right" type="submit">Guardar</button>
</form>
</div>
</div>