<h2>Agregar Categoria</h2>

<div class="container">
	<div class="col-sm-12 col-md-8 mx-auto">
<form action="<?php
/**
 * add.phtml
 *
 * @author Arturo Adonay Rayas Vergara <arturorayas60@gmail.com>
 */
 echo APP_URL.'categories/add'; ?>" method="POST">
	<div class="form-group">
		<label for="name">Nombre</label>
		<input class="form-control" type="text" name="name">
	</div>	
		<button class="btn btn-sm btn-success pull-right" action="submit">Guardar</button>
</form>
</div>
</div>