<h3>Listado de Categorias</h3>
<div class="container">
<a href="<?php
/**
 * update.phtml
 *
 * @author Arturo Adonay Rayas Vergara <arturorayas60@gmail.com>
 */

 echo APP_URL.'categories/add'; ?>">
	<button class="btn btn-sm btn-success"><i class="glyphicon glyphicon-plus"></i>Agregar categoria</button>	
</a>
<?php if (!empty($this->categories)): ?>
	<table class="table table-sm">
		<thead class="thead-light">
			<tr>
				<th>Nombre</th>
				<th>Opciones</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->categories as $category): ?>
				<tr>
					<td>
						<?php echo $category['name']; ?>
					</td>
					<td>
						<a href="<?php echo APP_URL.'categories/update/'.$category['id']; ?>">
							<button class="btn btn-sm btn-primary">
								<i class="glyphicon glyphicon-pencil"></i>
							</button>
						</a>
						<a href="<?php echo APP_URL.'categories/delete/'.$category['id']; ?>">
							<button class="btn btn-sm btn-danger confirmation">
								<i class="glyphicon glyphicon-trash"></i>
							</button>
						</a>
					</td>
				</tr>
			<?php endforeach ?>
		</tbody>
	</table>
<?php else: ?>
	<div>
		No hay categorias registradas
	</div>
<?php endif ?>
</div>