<h2>Lista de transacciones</h2>

<div class="container">
	<div class="col-md-12 text-right">

		<a href="<?php
/**
 * index.php vista transacciones
 *
 * @author Arturo Adonay Rayas Vergara <arturorayas60@gmail.com>
 */
echo APP_URL.'transactions/add'; ?>">
<button class="btn btn-sm btn-success pull-left">
			<i class="glyphicon glyphicon-plus"></i>
			Agregar Transacción
		</button>
</a>
</div>
<div class="col-md-12">
	<?php
	$cantIngresos=0;
	$cantEgresos=0;
	 if (!empty($this->transactions)): ?>
		<table class="table table-sm">
			<thead class="thead-light">
				<tr>
					<th>Cuenta</th>
					<th>Categoria</th>
					<th>Descripcion</th>
					<th>Fecha</th>
					<th>Monto</th>
					<th>Opciones</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->transactions as $transaction): ?>
					<tr>
						<td>
							<?php echo $transaction['nameaccount']; ?>
						</td>
						<td>
							<?php echo $transaction['namecategory']; ?>
						</td>
						<td>
							<?php echo $transaction['description']; ?>
						</td>
						<td>
							<?php 
							$date = date_create($transaction['date']);
							echo date_format($date,'d/m/Y');
							 ?>
						</td>
						<td>
							<?php 
								if ($transaction['amount'] > 0) 
								{
									$cantIngresos=$cantIngresos+$transaction['amount'];
									$money =number_format((float)$transaction['amount'] , 2, '.', '');
									echo "<label style='color:green'>"."$".$money."</label>";
								}
								if ($transaction['amount'] <0) 
								{	
									$cantEgresos=$cantEgresos+$transaction['amount'];
									$money =number_format((float)$transaction['amount'] , 2, '.', '');
									echo "<label style='color:red;'>"."$".$money."</label>";
								}
							?>	
						</td>
						<td>	
							<a href="<?php echo APP_URL.'transactions/update/'.$transaction['id']; ?>">
								<button class="btn btn-sm btn-primary">
									<i class="glyphicon glyphicon-pencil"></i>
								</button>
							</a>
							<a href="<?php echo APP_URL.'transactions/delete/'.$transaction['id']; ?>">
								<button class="btn btn-sm btn-danger confirmation">
									<i class="glyphicon glyphicon-trash"></i>
								</button>
							</a>
						</td>
					</tr>
				<?php endforeach ?>
			</tbody>
		</table>
		<div class="container">
			<div class="col-md-4 pull-right">
			<div class="form-group">
				<div class="col-xs-6 ">
				<label for="id_account">Cantidad Ingresos:</label>
				</div>
				<div class="col-xs-4 ">
				<?php  echo "<label>".$cantIngresos."</label>";?> 
				</div>
			</div>
			<div class="form-group">
				<div class="col-xs-6 ">
				<label for="id_account">Cantidad Egresos:</label>
				</div>
				<div class="col-xs-4">
				<?php  echo "<label>".$cantEgresos."</label>";?> 
				</div>
			</div>
			<div class="form-group">
				<div class="col-xs-6">
				<label for="id_account">Balance actual:</label>
				</div>
				<div class="col-xs-4">
				<?php
				$balance=0;
				$balance=$cantIngresos+$cantEgresos;
				if($balance>0){ echo "<label style='color:green;'>"."$".$balance."</label>";}
				else{ echo "<label style='color:red;'>"."$".$balance."</label>";}	
				 ?>
				</div>
			</div>
			</div>
		</div>
		<?php else: ?>
			<div>
				No hay registros
			</div>
		<?php endif ?>
	</div>
</div>