<h2>Editar transacción</h2>

<div class="container">
	<div class="col-sm-6 col-md-6 mx-auto">		
<form action="<?php
/**
 * update.phhtml
 *
 * @author Arturo Adonay Rayas Vergara <arturorayas60@gmail.com>
 */

 echo APP_URL.'transactions/update'; ?>" method="POST">
	<input type="hidden" name="id" value="<?php echo $this->transaction['id']; ?>">
	<div class="form-group">
		<label for="id_account">Cuenta</label>
		<select name="id_account" class="form-control">
			<?php foreach ($this->accounts as $account): ?>
				<?php echo "<option value='".$account['id']."'>".$account['name']."</option>"; ?>
			<?php endforeach ?>
		</select>
	</div>
	<div class="form-group">
		<label for="id_category">Categoria</label>
		<select name="id_category" class="form-control">
			<?php foreach ($this->categories as $category): ?>
				<?php echo "<option value='".$category['id']."''>".$category['name']."</option>"; ?>				
			<?php endforeach ?>
		</select>
	</div>
	<div class="form-group">
		<label for="date">Fecha</label>
		<input type="date" class="form-control" name="date" value="<?php echo date('Y-m-d'); ?>" value="<?php echo $this->transaction['date']; ?>">
	</div>
	<div class="form-group">
		<label for="description">Descripcion</label>
		<input type="text" class="form-control" name="description" value="<?php echo $this->transaction['description']; ?>">
	</div>
	<div class="form-group">
		<label for="amount">Monto</label>
		<input type="text" class="form-control" name="amount" value="<?php echo $this->transaction['amount']; ?>">
	</div>
		<button class="btn button btn-primary pull-right" type="submit">Guardar</button>
</form>
	</div>
</div>
